a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
print("The sum of this two number:",a+b)
print("The subtraction of this two number:",a-b)
print("The multipy of this two number:",a*b)
print("The divison of this two number:",a/b)
print("The divison(to find only vagfol)of this two number:",a//b)
print("The divison(to find only remainder)of this two number:",a%b)
print("The exponential of this two number:",a**b)
